// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzNV9OW_6l9eWp7irCTGooc7UBqNpprSk',
    appId: '1:234705916563:web:bc0ca45d85580280473366',
    messagingSenderId: '234705916563',
    projectId: 'my-project-183224',
    authDomain: 'my-project-183224.firebaseapp.com',
    storageBucket: 'my-project-183224.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8T7ZqlmHyax6P7p-GFf0guF-rrTccOZg',
    appId: '1:234705916563:android:a701218003ec1c5e473366',
    messagingSenderId: '234705916563',
    projectId: 'my-project-183224',
    storageBucket: 'my-project-183224.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgwjarOu7Y-kF36m-Jc2_ieySh1YP_oEk',
    appId: '1:234705916563:ios:d5138655519267a5473366',
    messagingSenderId: '234705916563',
    projectId: 'my-project-183224',
    storageBucket: 'my-project-183224.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgwjarOu7Y-kF36m-Jc2_ieySh1YP_oEk',
    appId: '1:234705916563:ios:d5138655519267a5473366',
    messagingSenderId: '234705916563',
    projectId: 'my-project-183224',
    storageBucket: 'my-project-183224.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzNV9OW_6l9eWp7irCTGooc7UBqNpprSk',
    appId: '1:234705916563:web:025a37f92453c9b0473366',
    messagingSenderId: '234705916563',
    projectId: 'my-project-183224',
    authDomain: 'my-project-183224.firebaseapp.com',
    storageBucket: 'my-project-183224.appspot.com',
  );
}
